### ISSUE TITLE
Friends requests not accepting

### ISSUE THREAD

**Issue by Appshure** [akirk/friends#99]
While trying to accept friends request from another blog, clicking "Accept request" refreshes the page but friends requests don't get accepted.

**Comment by Appshure** [comment]
Apologies for the late response.
Yes, it's on the same multisite, both users are administrators of their blogs.
No error message in the error log.

**Comment by BrendanAdkins** [comment]
I just wrote up a very similar issue on the support forum before discovering this repository. In my case, the request is functionally accepted--user A can see user B's posts in their Latest Posts page and vice versa. But the notification that there is a pending request persists, and clicking to accept it produces repeated status messages that all say "I'm now friends with A."

**Comment by uniphonic** [comment]
@BrendanAdkins , is it on a multisite? If so, if so I think it is a know issue with a fix that hasn't ben released yet.

**Comment by BrendanAdkins** [comment]
@uniphonic Yup, it is. Thank you, that's helpful to know. (It also seems to be the case that the "Friend" custom user role is not being applied correctly when the request is accepted!)

**Comment by akirk** [comment]
Sorry everybody, I've been quite busy otherwise recently. Version 2.0.0 with the fixes has been ready for a while, I've been just holding off because of some breaking changes to other plugins. I've released version 2.0.0 now, so that I hope this can be fixed for you.

In addition to the fix, I've also added support to the [Site Health function of WordPress](https://wordpress.org/support/article/site-health-screen/) which I hope will help diagnose problems like above a bit better.

**Comment by BrendanAdkins** [comment]
Excellent, thank you so much!

**Comment by akirk** [comment]
It would be excellent if you could confirm that things are better now or if we need to work on a follow-up fix.

**Comment by uniphonic** [comment]
@akirk , thanks for the updates! I just tried it out though, and unfortunately, for me it seems the issue still remains after the update. I had users already created from before the update, and after the update the friend requests seemed to be reset, so I tried sending the requests again:

1. User A sends a friend request to user B.
2. User B clicks Accept Friend Request.
3. The Friend Requests notification (red circle around the number 1) still exists even after accepting the friend request.

Should I try deleting the additional blogs and users I had created, to try to start from scratch?...

Actually, I just tried deleting users and blogs, and creating them again, but upon creating blogs and users again with the same names, before I sent any friend requests it looks as if one of the friend relationships still remains? Is it possible that when a blog and user get deleted that there is a separate table that keeps the relationships which isn't getting the user friend relationship data deleted?

I'll try to do some more testing again soon...

**Comment by akirk** [comment]
The notification is still there for the reason that the user role of user B remains "Friend Request" when it should change to "Friend". Is the role of user A still "Pending Friend Request" or does it change to "Friend"?

If this is the case, then the problem are not the user roles but the communication between the two sites. Do you have a multisite setup with subdomains or paths?

**Comment by uniphonic** [comment]
It's a multisite with paths. I'll have to check the other details...

**Comment by akirk** [comment]
I've now setup a multisite with sub-directories and while it generally worked, I realized that you might be using a Super Admin user which causes problems that I attempted to fix in #107.

At the same time, I've improved the multisite behavior in that no additional representative users are created for other users anymore.

While using the friends plugin in a multisite environment has been not intended (as in users befriending each other within the multisite), I understand that this is a use case that seems interesting.

**Comment by akirk** [comment]
It would be very helpful if you could use `git` to try out this branch and tell me if it improves things!

`git checkout improve-multisite-behavior` or download by downloading the plugin with these changes as ZIP file: https://github.com/akirk/friends/archive/refs/heads/improve-multisite-behavior.zip

**Comment by uniphonic** [comment]
OK, thanks @akirk ! I'm trying it out, and here is what I did:

1. First, I downloaded the zip.
2. I went to my site where I had the old version of the Friends plugin installed, and deactivated the plugin from the WordPress UI. 
3. Then I deleted the old Friends plugin from the WordPress UI.
4. Then I uploaded the new zip you gave above, via the WordPress UI, and Network activated the plugin.
5. Then I deleted the old child-sites I had created to try out the Friends plugin.
6. Then I deleted the old users I had created previously to try out the Friends Plugin.
7. Then I created new child-sites using the same user names and email addresses that I had previously used and deleted.
8. Then I logged out as the parent site super admin user, and logged in as a child site user, user A.
9. Sent a friend request to another child site user, user B.
10. Then logged in as user B.
11. Navigated to the Friend Requests, and then hovered over the user A name, and clicked the "Accept Friend Request" link.
12. After clicking it redirected me to the "All users" screen that showed the list of two user names (user A and user B), and it showed user B role as Admin, and user A role as "None".
13. I refreshed the page, and now it only shows the Users screen with user A showing the Role as "None" (user B who is the logged in user is no longer present in the list).
14. The "Friend Requests" menu item in the left navigation still has a red circle with a "1" in it.
15. Repeating accepting the friend request again has the same results, and still shows the red circle with a 1 in it, and still shows the accepted friend's role as "None".
<img width="188" alt="Screen Shot 2022-04-15 at 1 48 59 PM" src="https://user-images.githubusercontent.com/1877731/163603919-67f54954-8084-498e-98b6-f4189cd11d21.png">

Anything additional I should try?

Thank you!

**Comment by akirk** [comment]
Thank you @uniphonic for helping debug this and the detailed steps. I've followed the exact same steps on my local setup and it worked.

> After clicking it redirected me to the "All users" screen that showed the list of two user names (user A and user B), and it showed user B role as Admin, and user A role as "None".

As you might have already assumed, here is where things go wrong (and differently than on my own setup).

Could you log in as Super Admin and navigate to the wp-admin each site and check the Tools > Site Health page and check on both the first and second tab what you find in the Friends section (on the first page it will only show if a check failed)? Maybe you can even click the "Copy site info to clipboard" and paste it to https://wpfriends.at/get-in-touch/ to send me some more debug info? Thank you!

**Comment by uniphonic** [comment]
Thanks, @akirk ! Under the Site Health I'm seeing:


Friends Version | 2.0.2
-- | --
mbstring is available | Yes
Friend roles exist | No
Main Friend User | #17 myfriendname
Registered Parsers | SimplePie, Microformats, JSON Feed

This didn't seem to show any errors, so I sent you the full Site Health Info paste to your site contact form, as requested. Does that shed any light?

Thanks!

**Comment by akirk** [comment]
Thank you, this was very helpful! Actually the "Friend roles exist: No" already explains what's wrong, i.e. the activation of the plugin didn't generate the roles as expected.

I have updated the ZIP https://github.com/akirk/friends/archive/refs/heads/improve-multisite-behavior.zip that fixes a test on the main site health page. You should now see this and the link will hopefully fix the problem for you:
<img width="815" alt="Screenshot 2022-04-24 at 21 09 37" src="https://user-images.githubusercontent.com/203408/164992571-209db131-b54d-4b38-a63b-0c66e3cd631e.png">

If not, then the code for creating the roles is not working as expected and we'll need to find a way to fix that. Thank you for helping with debugging this!

**Comment by autisticjane** [comment]
I am also experiencing this, but do not use Multisite.

On my personal blog, I accepted the friend request, but it's still pending on another blog. Site health info (I'm mobile, so it's not pretty):

Friends Version
2.1.3
mbstring is available
Yes
Friend roles missing
All roles found: friend, pending_friend_request, friend_request, subscription
Main Friend User
#1 mer
Registered Parsers
SimplePie, Microformats, JSON Feed
